server:
  port: 8080

spring:
  datasource:
    url: ${POSTGRES_URL}EventHub
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

image:
  upload-dir: src/main/uploads

logging:
  level:
    root: INFO
    com.example: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %5p [%t] %c{1}:%L - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %5p [%t] %c{1}:%L - %m%n"

